![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
import numpy as np
my_array = np.arange(10)
print(my_array[9::-2]) 

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [4]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [85]:

import numpy as np


array_4 = np.arange(1, 21).reshape(4, 5)
print("Array:", array_4)
array_4_inv = array_4[::-1, ::-1]   
print()      
print("Array invertida:", array_4_inv)
print()  
print()  

print(np.flip(array_4))

Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Array invertida: [[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [13]:
array_5 = array_4[:2, :2]
print(array_5)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [14]:
array_6 = array_4[::2, ::2]  
print(array_6)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [16]:
array_7 = array_4[:3, ::-1]
print(array_7)


[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:

x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])


array_8_1 = x[x == "Loro"]

array_8_2 = np.extract(x == "Loro",x)


print(array_8_1)  
print(array_8_2) 


['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [26]:
import numpy as np

secuencia = np.arange(20)
print(secuencia)

array_9 = secuencia.reshape(2, 5, 2)

print(array_9.shape)  
print(array_9)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(2, 5, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [29]:
array_10 = array_4[::-1, ::-1]  
print(array_10)


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [88]:

array_10 = np.zeros(10)    
print("Tamaño:", array_10.size)        
print("Espacio en memoria cada elemento:", array_10.itemsize, "bytes por elemento")
print("Espacio en memmoria total:", array_10.nbytes, "bytes en total")  

array_10[3] = 1
print(array_10)


Tamaño: 10
Espacio en memoria cada elemento: 8 bytes por elemento
Espacio en memmoria total: 80 bytes en total
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [89]:

array_12 = np.arange(10, 50)  
print(array_12)       

array_12_inv = array_12[::-1]        
print(array_12_inv)  


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [55]:
array_14 = np.random.randint(1, 200, size=(10, 10))


print(array_14)

min = array_14.min()        
max = array_14.max()       

print("Mínimo:", min)
print("Máximo:", max)


[[  9  35  47  43  99  78 132  15 126 102]
 [144 189 168  29 108 188  51 169  18  30]
 [ 95   8  28  23   8  71  19  37 183 133]
 [198 111 150  75  97  30  38  65 136 172]
 [162  69 116  14   3  43  95  94 107  68]
 [ 46  20 153 163  20  81 136  69 140  51]
 [153  92  33 126 183  68  17 127   8 189]
 [101  74 141  35  10  87 172 177  54  12]
 [165  11 148 163 102  35  59 129  38  67]
 [ 14 156 177 134  89  97  19  59 130 149]]
Mínimo: 3
Máximo: 198


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [58]:
array_15 = np.random.randint(1, 101, size=30)

print(array_15)
print()

media = np.mean(array_15)

print(media)


[15 56  1 33 10 66 22 59 62  8  3 93 55 81 23 38 74 38 97 40 67 99 10 49
 79 74 11 99 77 15]

48.46666666666667


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [60]:
array = np.zeros((8, 8), dtype=int)
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print()
print(array)
print()


[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]



## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [63]:

array_17 = np.zeros((8, 8), dtype=int)

array_17_1 = np.indices((8, 8)).sum(axis=0) % 2

print(array_17_1)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [90]:
array_17 = np.array([[0, 1], [1, 0]])                 
print(array_17)
print()
array_17_1 = np.tile(array_17, (4,4))
print(array_17_1)

[[0 1]
 [1 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [78]:

matriz_original = np.random.randint(1, 101, size=(5, 5))


print(matriz_original)
print()


media = np.mean(matriz_original)
desviacion = np.std(matriz_original)

print(f"Media:{media}")
print(f"Desviación estándar: {desviacion}")
print()


matriz_estandarizada = (matriz_original - media) / desviacion

print("Matriz estandarizada:")
print(matriz_estandarizada)
print()


[[45 43 54 51 62]
 [ 7 94 31 65 79]
 [47 49 61  8 56]
 [58 71 26 56 75]
 [34 41 73 50 88]]

Media:52.96
Desviación estándar: 21.17636418273921

Matriz estandarizada:
[[-0.37589078 -0.4703357   0.04911136 -0.09255602  0.42689103]
 [-2.17034424  1.93800974 -1.03700521  0.56855841  1.22967285]
 [-0.28144586 -0.18700094  0.37966857 -2.12312178  0.14355628]
 [ 0.2380012   0.85189317 -1.27311751  0.14355628  1.04078301]
 [-0.89533783 -0.56478062  0.94633809 -0.13977848  1.65467498]]



## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [80]:


array_19 = np.arange(11)

print(array_19)
print()

array_sustituido = array_19.copy()
array_sustituido[(array_sustituido >= 3) & (array_sustituido <= 8)] = -1

print(array_sustituido)
print()

array_negado = array_19.copy()
mascara = (array_negado >= 3) & (array_negado <= 8)
array_negado[mascara] = -array_negado[mascara]

print(array_negado)
print()

[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]

